### PR TITLE
Proposition of the DQL API

### PR DESCRIPTION
**Pull request by lscharmer**

### CODE REVIEW

**Comment by mjansenDatabay** [comment]
Please add some unit test when suggesting the final PR for `trunk` later. IMO we should add a new `integrity()`-Method to the `ilDBInterface`, which returns an instance of `Integrity`. Furthermore `Integrety` should maybe used as a location for furthere methods to add/delete/checkForExistence of `Foreign Key` definitions.

**Comment by lscharmer** [comment]
> Please add some unit test when suggesting the final PR for `trunk` later. IMO we should add a new `integrity()`-Method to the `ilDBInterface`, which returns an instance of `Integrity`. Furthermore `Integrety` should maybe used as a location for furthere methods to add/delete/checkForExistence of `Foreign Key` definitions.

Yes, this is just the first revision, unit tests and stuff will be added when it is clear how the API should look like.

**Comment by lscharmer** [comment]
@gvollbach push

**Comment by lscharmer** [comment]
@gvollbach pUsH

**Pull request closed without merging**
